### ISSUE TITLE
Sort By Category

### ISSUE THREAD

**Issue by Ryanb58** [Ryanb58/the-colossal-saas-list#1]
How about sorting the list by category instead of alphabetically. This would help readability and useability.

**Comment by Ryanb58** [comment]
What categories should there be?

**Comment by itsthejoker** [comment]
I suggest that categories be decided simply by what kind of offerings there are on the list. For example, we have "File Hosting" for Dropbox, "Web Registrar" for GoDaddy, and "VPS" for DigitalOcean. If you come across a company that can't adequately be sorted into the categories you have, you can just add another category.
